# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-3
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib D:/xy/crc_test/vivado_prj/crc_test/crc_test.srcs/sources_1/imports/design/crc3.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/xy/crc_test/vivado_prj/crc_test/crc_test.cache/wt [current_project]
set_property parent.project_dir D:/xy/crc_test/vivado_prj/crc_test [current_project]
catch { write_hwdef -file crc3.hwdef }
synth_design -top crc3 -part xc7a35tcpg236-3
write_checkpoint crc3.dcp
report_utilization -file crc3_utilization_synth.rpt -pb crc3_utilization_synth.pb
